/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {Address, AuditLogEntryAddress, Pageable, PageAddress} from '../model/models';


import {Configuration} from '../configuration';


export interface AddressControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param pageable
   */
  audit(pageable: Pageable, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryAddress>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryAddress>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param address
   */
  create(address: Address, extraHttpRequestParams?: any): Observable<Address>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<Address>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageAddress>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @param id
   * @param address
   */
  update(id: number, address: Address, extraHttpRequestParams?: any): Observable<Address>;

}
