export * from './fsNodeController.service';
import { FsNodeControllerService } from './fsNodeController.service';
export * from './fsNodeController.serviceInterface';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './loginController.serviceInterface';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './userController.serviceInterface';
export const APIS = [FsNodeControllerService, LoginControllerService, UserControllerService];
