export * from './droneController.service';
import { DroneControllerService } from './droneController.service';
export * from './droneController.serviceInterface';
export * from './flightTaskController.service';
import { FlightTaskControllerService } from './flightTaskController.service';
export * from './flightTaskController.serviceInterface';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './loginController.serviceInterface';
export * from './medicalFacilityController.service';
import { MedicalFacilityControllerService } from './medicalFacilityController.service';
export * from './medicalFacilityController.serviceInterface';
export * from './noFlightZoneController.service';
import { NoFlightZoneControllerService } from './noFlightZoneController.service';
export * from './noFlightZoneController.serviceInterface';
export * from './productTypeController.service';
import { ProductTypeControllerService } from './productTypeController.service';
export * from './productTypeController.serviceInterface';
export * from './requestController.service';
import { RequestControllerService } from './requestController.service';
export * from './requestController.serviceInterface';
export * from './requestEntryController.service';
import { RequestEntryControllerService } from './requestEntryController.service';
export * from './requestEntryController.serviceInterface';
export * from './routeController.service';
import { RouteControllerService } from './routeController.service';
export * from './routeController.serviceInterface';
export * from './typeOfDroneController.service';
import { TypeOfDroneControllerService } from './typeOfDroneController.service';
export * from './typeOfDroneController.serviceInterface';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './userController.serviceInterface';
export * from './warehouseController.service';
import { WarehouseControllerService } from './warehouseController.service';
export * from './warehouseController.serviceInterface';
export const APIS = [DroneControllerService, FlightTaskControllerService, LoginControllerService, MedicalFacilityControllerService, NoFlightZoneControllerService, ProductTypeControllerService, RequestControllerService, RequestEntryControllerService, RouteControllerService, TypeOfDroneControllerService, UserControllerService, WarehouseControllerService];
