/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FsNodeDto } from '../model/models';
import { PageFsNodeDto } from '../model/models';
import { Pageable } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FsNodeControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    count(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param fsNodeDto 
     */
    create(fsNodeDto: FsNodeDto, extraHttpRequestParams?: any): Observable<FsNodeDto>;

    /**
     * 
     * 
     * @param id 
     */
    get(id: number, extraHttpRequestParams?: any): Observable<FsNodeDto>;

    /**
     * 
     * 
     * @param pageable 
     * @param filter 
     */
    list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageFsNodeDto>;

    /**
     * 
     * 
     */
    listAll(extraHttpRequestParams?: any): Observable<Array<FsNodeDto>>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @param id 
     * @param fsNodeDto 
     */
    update(id: number, fsNodeDto: FsNodeDto, extraHttpRequestParams?: any): Observable<FsNodeDto>;

}
