/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AuditLogEntryLocation, LocationDto, Pageable, PageLocationDto} from '../model/models';


import {Configuration} from '../configuration';


export interface LocationControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param pageable
   */
  audit(pageable: Pageable, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryLocation>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryLocation>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param locationDto
   */
  create(locationDto: LocationDto, extraHttpRequestParams?: any): Observable<LocationDto>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<LocationDto>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageLocationDto>;

  /**
   *
   *
   */
  listAll(extraHttpRequestParams?: any): Observable<Array<LocationDto>>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @param id
   * @param locationDto
   */
  update(id: number, locationDto: LocationDto, extraHttpRequestParams?: any): Observable<LocationDto>;

}
