/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {LoginDto, RegisterDto, UserRsDto} from '../model/models';


import {Configuration} from '../configuration';


export interface LoginControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param loginDto
   */
  login(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<UserRsDto>;

  /**
   *
   *
   * @param registerDto
   */
  register(registerDto: RegisterDto, extraHttpRequestParams?: any): Observable<UserRsDto>;

}
