/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AuditLogEntryOrganization, OrganizationDto, Pageable, PageOrganizationDto} from '../model/models';


import {Configuration} from '../configuration';


export interface OrganizationControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param pageable
   */
  audit(pageable: Pageable, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryOrganization>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryOrganization>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param organizationDto
   */
  create(organizationDto: OrganizationDto, extraHttpRequestParams?: any): Observable<OrganizationDto>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<OrganizationDto>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageOrganizationDto>;

  /**
   *
   *
   */
  listAll(extraHttpRequestParams?: any): Observable<Array<OrganizationDto>>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @param id
   * @param organizationDto
   */
  update(id: number, organizationDto: OrganizationDto, extraHttpRequestParams?: any): Observable<OrganizationDto>;

}
