/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AuditLogEntryPerson, Pageable, PagePerson, Person} from '../model/models';


import {Configuration} from '../configuration';


export interface PersonControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param id
   */
  _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   */
  audit(extraHttpRequestParams?: any): Observable<Array<AuditLogEntryPerson>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryPerson>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param person
   */
  create(person: Person, extraHttpRequestParams?: any): Observable<Person>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<Person>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PagePerson>;

  /**
   *
   *
   * @param id
   * @param person
   */
  update(id: number, person: Person, extraHttpRequestParams?: any): Observable<Person>;

}
