/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AuditLogEntryPerson, Pageable, PagePersonDto, PersonDto} from '../model/models';


import {Configuration} from '../configuration';


export interface PersonControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param pageable
   */
  audit(pageable: Pageable, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryPerson>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryPerson>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param personDto
   */
  create(personDto: PersonDto, extraHttpRequestParams?: any): Observable<PersonDto>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<PersonDto>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PagePersonDto>;

  /**
   *
   *
   */
  listAll(extraHttpRequestParams?: any): Observable<Array<PersonDto>>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @param id
   * @param personDto
   */
  update(id: number, personDto: PersonDto, extraHttpRequestParams?: any): Observable<PersonDto>;

}
