/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {AuditLogEntryProduct, Pageable, PageProductDto, Product, ProductDto} from '../model/models';


import {Configuration} from '../configuration';


export interface ProductControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param pageable
   */
  audit(pageable: Pageable, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryProduct>>;

  /**
   *
   *
   * @param id
   */
  auditItem(id: number, extraHttpRequestParams?: any): Observable<Array<AuditLogEntryProduct>>;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param personId
   */
  countProductsLessThanOwner(personId: number, extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param productDto
   */
  create(productDto: ProductDto, extraHttpRequestParams?: any): Observable<ProductDto>;

  /**
   *
   *
   * @param percent
   */
  decreaseProductPricesBy(percent: number, extraHttpRequestParams?: any): Observable<boolean>;

  /**
   *
   *
   */
  findProductWithMaxManufactureCost(extraHttpRequestParams?: any): Observable<Product>;

  /**
   *
   *
   * @param partNumber
   */
  findProductsWithPartNumberGreaterThan(partNumber: string, extraHttpRequestParams?: any): Observable<Array<Product>>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<ProductDto>;

  /**
   *
   *
   * @param unitOfMeasures
   */
  getProductsByUnitOfMeasure(unitOfMeasures: Array<'METERS' | 'CENTIMETERS' | 'MILLILITERS'>, extraHttpRequestParams?: any): Observable<Array<Product>>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageProductDto>;

  /**
   *
   *
   */
  listAll(extraHttpRequestParams?: any): Observable<Array<ProductDto>>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @param id
   * @param productDto
   */
  update(id: number, productDto: ProductDto, extraHttpRequestParams?: any): Observable<ProductDto>;

}
