/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {Pageable, PageRequestEntryDto, RequestEntryDto} from '../model/models';


import {Configuration} from '../configuration';


export interface RequestEntryControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  count(extraHttpRequestParams?: any): Observable<number>;

  /**
   *
   *
   * @param requestEntryDto
   */
  create(requestEntryDto: RequestEntryDto, extraHttpRequestParams?: any): Observable<RequestEntryDto>;

  /**
   *
   *
   * @param id
   */
  get(id: number, extraHttpRequestParams?: any): Observable<RequestEntryDto>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageRequestEntryDto>;

  /**
   *
   *
   */
  listAll(extraHttpRequestParams?: any): Observable<Array<RequestEntryDto>>;

  /**
   *
   *
   * @param id
   */
  remove(id: number, extraHttpRequestParams?: any): Observable<boolean>;

  /**
   *
   *
   * @param id
   * @param requestEntryDto
   */
  update(id: number, requestEntryDto: RequestEntryDto, extraHttpRequestParams?: any): Observable<RequestEntryDto>;

}
