/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {Pageable, PageUser, User} from '../model/models';


import {Configuration} from '../configuration';


export interface UserControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  get(extraHttpRequestParams?: any): Observable<User>;

  /**
   *
   *
   * @param pageable
   * @param filter
   */
  list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageUser>;

  /**
   *
   *
   * @param id
   */
  verifyAdmin(id: number, extraHttpRequestParams?: any): Observable<User>;

}
