/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageWarehouseProductsDto } from '../model/models';
import { Pageable } from '../model/models';
import { WarehouseProductsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WarehouseProductsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param warehouseProductsDto 
     */
    create(warehouseProductsDto: WarehouseProductsDto, extraHttpRequestParams?: any): Observable<WarehouseProductsDto>;

    /**
     * 
     * 
     * @param pageable 
     * @param filter 
     */
    list(pageable: Pageable, filter?: string, extraHttpRequestParams?: any): Observable<PageWarehouseProductsDto>;

    /**
     * 
     * 
     * @param id 
     * @param warehouseProductsDto 
     */
    update(id: number, warehouseProductsDto: WarehouseProductsDto, extraHttpRequestParams?: any): Observable<WarehouseProductsDto>;

}
