/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Organization} from './organization';


export interface AuditLogEntryOrganization {
  timestamp: string;
  author: number;
  revision: number;
  type: AuditLogEntryOrganization.TypeEnum;
  state: Organization;
}

export namespace AuditLogEntryOrganization {
  export type TypeEnum = 'ADD' | 'MOD' | 'DEL';
  export const TypeEnum = {
    Add: 'ADD' as TypeEnum,
    Mod: 'MOD' as TypeEnum,
    Del: 'DEL' as TypeEnum
  };
}


