/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DroneDto {
  typeOfDroneName?: string;
  status?: DroneDto.StatusEnum;
  locationLat?: number;
  locationLon?: number;
  flightTaskId?: number;
  id?: number;
}

export namespace DroneDto {
  export type StatusEnum = 'IDLE' | 'READY' | 'FLYING_TO' | 'FLYING_FROM';
  export const StatusEnum = {
    Idle: 'IDLE' as StatusEnum,
    Ready: 'READY' as StatusEnum,
    FlyingTo: 'FLYING_TO' as StatusEnum,
    FlyingFrom: 'FLYING_FROM' as StatusEnum
  };
}


