/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Geometry} from './geometry';
import {BoundingBox} from './boundingBox';


export interface Feature {
  geometry?: Geometry;
  properties: { [key: string]: object; };
  id?: string;
  bbox?: BoundingBox;
}

