/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeDto } from './productTypeDto';
import { RequestDto } from './requestDto';
import { MedicalFacilityDto } from './medicalFacilityDto';
import { RouteDto } from './routeDto';
import { WarehouseDto } from './warehouseDto';


export interface FlightTaskDto { 
    request?: RequestDto;
    status?: FlightTaskDto.StatusEnum;
    productType?: ProductTypeDto;
    warehouse?: WarehouseDto;
    medicalFacility?: MedicalFacilityDto;
    quantity?: number;
    route?: RouteDto;
    timestamp?: string;
    id?: number;
}
export namespace FlightTaskDto {
    export type StatusEnum = 'QUEUED' | 'READY' | 'PACKING' | 'IN_PROGRESS' | 'COMPLETED';
    export const StatusEnum = {
        Queued: 'QUEUED' as StatusEnum,
        Ready: 'READY' as StatusEnum,
        Packing: 'PACKING' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum
    };
}


