/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FsNode } from './fsNode';
import { NodePermission } from './nodePermission';


export interface FsNodeDto { 
    id?: number;
    name?: string;
    fileId?: string;
    ownerUid?: number;
    ownerGid?: number;
    accessRights?: NodePermission;
    isDirectory?: boolean;
    createdAt?: string;
    modifiedAt?: string;
    parentId?: number;
    children: Array<FsNode>;
}

