/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Address} from './address';


export interface Organization {
  name: string;
  officialAddress?: Address;
  annualTurnover?: number;
  employeesCount: number;
  fullName: string;
  type?: Organization.TypeEnum;
  postalAddress?: Address;
  id?: number;
}

export namespace Organization {
  export type TypeEnum = 'COMMERCIAL' | 'PUBLIC' | 'GOVERNMENT' | 'TRUST' | 'PRIVATE_LIMITED_COMPANY';
  export const TypeEnum = {
    Commercial: 'COMMERCIAL' as TypeEnum,
    Public: 'PUBLIC' as TypeEnum,
    Government: 'GOVERNMENT' as TypeEnum,
    Trust: 'TRUST' as TypeEnum,
    PrivateLimitedCompany: 'PRIVATE_LIMITED_COMPANY' as TypeEnum
  };
}


