/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {User} from './user';
import {Location} from './location';


export interface Person {
  name: string;
  eyeColor: Person.EyeColorEnum;
  hairColor?: Person.HairColorEnum;
  location?: Location;
  height: number;
  nationality?: Person.NationalityEnum;
  id?: number;
  owner?: User;
}

export namespace Person {
  export type EyeColorEnum = 'GREEN' | 'BLUE' | 'YELLOW';
  export const EyeColorEnum = {
    Green: 'GREEN' as EyeColorEnum,
    Blue: 'BLUE' as EyeColorEnum,
    Yellow: 'YELLOW' as EyeColorEnum
  };
  export type HairColorEnum = 'GREEN' | 'BLUE' | 'YELLOW';
  export const HairColorEnum = {
    Green: 'GREEN' as HairColorEnum,
    Blue: 'BLUE' as HairColorEnum,
    Yellow: 'YELLOW' as HairColorEnum
  };
  export type NationalityEnum = 'RUSSIA' | 'SPAIN' | 'VATICAN' | 'NORTH_KOREA' | 'JAPAN';
  export const NationalityEnum = {
    Russia: 'RUSSIA' as NationalityEnum,
    Spain: 'SPAIN' as NationalityEnum,
    Vatican: 'VATICAN' as NationalityEnum,
    NorthKorea: 'NORTH_KOREA' as NationalityEnum,
    Japan: 'JAPAN' as NationalityEnum
  };
}


