/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PersonDto} from './personDto';
import {OrganizationDto} from './organizationDto';


export interface ProductDto {
  name: string;
  coordinateX: number;
  coordinateY: number;
  creationDate?: string;
  unitOfMeasure?: ProductDto.UnitOfMeasureEnum;
  manufacturer?: OrganizationDto;
  price: number;
  manufactureCost: number;
  rating: number;
  partNumber: string;
  personOwner?: PersonDto;
  id?: number;
  ownerUsername?: string;
  ownerId?: number;
}

export namespace ProductDto {
  export type UnitOfMeasureEnum = 'METERS' | 'CENTIMETERS' | 'MILLILITERS';
  export const UnitOfMeasureEnum = {
    Meters: 'METERS' as UnitOfMeasureEnum,
    Centimeters: 'CENTIMETERS' as UnitOfMeasureEnum,
    Milliliters: 'MILLILITERS' as UnitOfMeasureEnum
  };
}


