/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Organization} from './organization';
import {Coordinates} from './coordinates';
import {Person} from './person';


export interface Product {
  name: string;
  coordinates: Coordinates;
  creationDate: string;
  unitOfMeasure?: Product.UnitOfMeasureEnum;
  manufacturer?: Organization;
  price: number;
  manufactureCost: number;
  rating: number;
  partNumber: string;
  owner?: Person;
  id?: number;
}

export namespace Product {
  export type UnitOfMeasureEnum = 'METERS' | 'CENTIMETERS' | 'MILLILITERS';
  export const UnitOfMeasureEnum = {
    Meters: 'METERS' as UnitOfMeasureEnum,
    Centimeters: 'CENTIMETERS' as UnitOfMeasureEnum,
    Milliliters: 'MILLILITERS' as UnitOfMeasureEnum
  };
}


