/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto {
  username: string;
  password: string;
  role: RegisterDto.RoleEnum;
}

export namespace RegisterDto {
  export type RoleEnum = 'USER' | 'ADMIN' | 'ADMIN_PENDING';
  export const RoleEnum = {
    User: 'USER' as RoleEnum,
    Admin: 'ADMIN' as RoleEnum,
    AdminPending: 'ADMIN_PENDING' as RoleEnum
  };
}


