/**
 * ITMO Lab1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRsDto { 
    username: string;
    role: UserRsDto.RoleEnum;
    token: string;
}
export namespace UserRsDto {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MEDIC' | 'WAREHOUSE';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Medic: 'MEDIC' as RoleEnum,
        Warehouse: 'WAREHOUSE' as RoleEnum
    };
}


